name: Test Self-Hosted Runner
on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Runner check
        run: |
          echo "Runner is working"
          whoami
          uname -a
          hostname
